image: Visual Studio 2015

environment:
  host: x86_64-pc-windows-msvc
  matrix:
    - platform: arm64
      target: aarch64-unknown-linux-gnu
      channel: nightly

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - appveyor DownloadFile https://people.xiph.org/~tdaede/nasm-2.14.02-win64.zip -FileName nasm.zip
    - appveyor DownloadFile https://github.com/mozilla/sccache/releases/download/0.2.11/sccache-0.2.11-x86_64-pc-windows-msvc.tar.gz
    - tar xzf sccache-0.2.11-x86_64-pc-windows-msvc.tar.gz
    - 7z e -y nasm.zip
    - rustup-init -yv --default-toolchain %channel% --default-host %host%
    - set PATH=%PATH%;%CLPATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%;nasm-2.14.02;sccache-0.2.11-x86_64-pc-windows-msvc;
    - set RUSTC_WRAPPER=sccache
    - set SCCACHE_CACHE_SIZE=500M
    - set SCCACHE_DIR=%LOCALAPPDATA%\Mozilla\sccache
    - rustc -vV
    - cargo -vV
    - rustup target add %target%
    - echo %PATH%

on_success:
    - sccache -s

cache:
    - '%LOCALAPPDATA%\Mozilla\sccache'

build_script:
    - cargo build --manifest-path=aarch64/Cargo.toml --no-default-features --release --target=%target%

test_script:
    - cargo test --manifest-path=aarch64/Cargo.toml --release --target=%target% --verbose
